[workspace]
members = [
    "app",
    "common",
    "test-tar",
    "test-snappy",
    "test-gzip",
    "test-zstd",
    "test-zip_br",
]

[workspace.dependencies]
anyhow = "1"
humansize = "2.1"
rayon = "1"
tokio = "1"