[package]
name = "test-zip_gzip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bytes = "1"
common = { path = "../common" }
zip = { workspace = true }
flate2 = "1"